//go:build exclude

// this file is autogenerated by __FILE__ do not edit

package at

import (
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"kitty/tools/cli"
	"kitty/tools/utils"
)

type options_CMD_NAME_type struct {
	OPTIONS_DECLARATION_CODE
}

var options_CMD_NAME options_CMD_NAME_type

func run_CMD_NAME(cmd *cobra.Command, args []string) (err error) {
	SET_OPTION_VALUES_CODE

	rc := utils.RemoteControlCmd{
		Cmd:        "CLI_NAME",
		Version:    [3]int{0, 20, 0},
		NoResponse: NO_RESPONSE_BASE,
	}
	nrv, err := cmd.Flags().GetBool("no-response")
	if err == nil {
		rc.NoResponse = nrv
	}
	err = send_rc_command(&rc, WAIT_TIMEOUT)
	return
}

func aliasNormalizeFunc_CMD_NAME(f *pflag.FlagSet, name string) pflag.NormalizedName {
	name = cli.FlagNormalizer(name)
	ALIAS_NORMALIZE_CODE
	return pflag.NormalizedName(name)
}

func setup_CMD_NAME(root *cobra.Command) *cobra.Command {
	ans := cli.CreateCommand(&cobra.Command{
		Use:   "CLI_NAME [options]",
		Short: "SHORT_DESC",
		Long:  "LONG_DESC",
		RunE:  run_CMD_NAME,
	})
	ADD_FLAGS_CODE
	ans.Flags().SetNormalizeFunc(aliasNormalizeFunc_CMD_NAME)

	return ans
}

func init() {
	all_commands["CMD_NAME"] = setup_CMD_NAME
}
