#define DO_FG_OVERRIDE {DO_FG_OVERRIDE}
#define FG_OVERRIDE_THRESHOLD {FG_OVERRIDE_THRESHOLD}
#define FG_OVERRIDE_ALGO {FG_OVERRIDE_ALGO}
#define TEXT_NEW_GAMMA {TEXT_NEW_GAMMA}

#define DECORATION_SHIFT {DECORATION_SHIFT}
#define REVERSE_SHIFT {REVERSE_SHIFT}
#define STRIKE_SHIFT {STRIKE_SHIFT}
#define DIM_SHIFT {DIM_SHIFT}
#define BLINK_SHIFT {BLINK_SHIFT}
#define MARK_SHIFT {MARK_SHIFT}
#define MARK_MASK {MARK_MASK}
#define USE_SELECTION_FG
#define NUM_COLORS 256
#define COLOR_NOT_SET {COLOR_NOT_SET}
#define COLOR_IS_SPECIAL {COLOR_IS_SPECIAL}
#define COLOR_IS_RGB {COLOR_IS_RGB}
#define COLOR_IS_INDEX {COLOR_IS_INDEX}

#if {ONLY_BACKGROUND} == 1
#define ONLY_BACKGROUND
#endif

#if {ONLY_FOREGROUND} == 1
#define ONLY_FOREGROUND
#endif

// Linear space luminance values
const vec3 Y = vec3(0.2126, 0.7152, 0.0722);
