# Update this file by running: python kitty/options_stub.py
import kitty.rgb
from kitty.rgb import Color
import typing


class Options:
    font_family: str
    bold_font: str
    italic_font: str
    bold_italic_font: str
    font_size: float
    force_ltr: bool
    adjust_line_height: typing.Union[int, float]
    adjust_column_width: typing.Union[int, float]
    symbol_map: typing.Dict[typing.Tuple[int, int], str]
    disable_ligatures: int
    font_features: str
    box_drawing_scale: typing.Tuple[float, float, float, float]
    cursor: Color
    cursor_text_color: typing.Union[kitty.rgb.Color, None]
    cursor_shape: int
    cursor_beam_thickness: float
    cursor_underline_thickness: float
    cursor_blink_interval: float
    cursor_stop_blinking_after: float
    scrollback_lines: int
    scrollback_pager: typing.List[str]
    scrollback_pager_history_size: int
    wheel_scroll_multiplier: float
    touch_scroll_multiplier: float
    mouse_hide_wait: float
    url_color: Color
    url_style: int
    open_url_modifiers: int
    open_url_with: typing.List[str]
    copy_on_select: str
    strip_trailing_spaces: str
    rectangle_select_modifiers: int
    terminal_select_modifiers: int
    select_by_word_characters: str
    click_interval: float
    focus_follows_mouse: bool
    pointer_shape_when_grabbed: str
    repaint_delay: int
    input_delay: int
    sync_to_monitor: bool
    enable_audio_bell: bool
    visual_bell_duration: float
    window_alert_on_bell: bool
    bell_on_tab: bool
    command_on_bell: typing.List[str]
    remember_window_size: bool
    initial_window_width: typing.Tuple[int, str]
    initial_window_height: typing.Tuple[int, str]
    enabled_layouts: typing.List[str]
    window_resize_step_cells: int
    window_resize_step_lines: int
    window_border_width: float
    draw_minimal_borders: bool
    window_margin_width: float
    single_window_margin_width: float
    window_padding_width: float
    placement_strategy: str
    active_border_color: typing.Union[kitty.rgb.Color, None]
    inactive_border_color: Color
    bell_border_color: Color
    inactive_text_alpha: float
    hide_window_decorations: int
    resize_debounce_time: float
    resize_draw_strategy: int
    resize_in_steps: bool
    tab_bar_edge: int
    tab_bar_margin_width: float
    tab_bar_style: str
    tab_bar_min_tabs: int
    tab_switch_strategy: str
    tab_fade: typing.Tuple[float, ...]
    tab_separator: str
    tab_title_template: str
    active_tab_title_template: typing.Union[str, None]
    active_tab_foreground: Color
    active_tab_background: Color
    active_tab_font_style: typing.Tuple[bool, bool]
    inactive_tab_foreground: Color
    inactive_tab_background: Color
    inactive_tab_font_style: typing.Tuple[bool, bool]
    tab_bar_background: typing.Union[kitty.rgb.Color, None]
    foreground: Color
    background: Color
    background_opacity: float
    background_image: typing.Union[str, None]
    background_image_layout: str
    background_image_linear: bool
    dynamic_background_opacity: bool
    background_tint: float
    dim_opacity: float
    selection_foreground: typing.Union[kitty.rgb.Color, None]
    selection_background: Color
    color0: Color
    color8: Color
    color1: Color
    color9: Color
    color2: Color
    color10: Color
    color3: Color
    color11: Color
    color4: Color
    color12: Color
    color5: Color
    color13: Color
    color6: Color
    color14: Color
    color7: Color
    color15: Color
    mark1_foreground: Color
    mark1_background: Color
    mark2_foreground: Color
    mark2_background: Color
    mark3_foreground: Color
    mark3_background: Color
    color16: Color
    color17: Color
    color18: Color
    color19: Color
    color20: Color
    color21: Color
    color22: Color
    color23: Color
    color24: Color
    color25: Color
    color26: Color
    color27: Color
    color28: Color
    color29: Color
    color30: Color
    color31: Color
    color32: Color
    color33: Color
    color34: Color
    color35: Color
    color36: Color
    color37: Color
    color38: Color
    color39: Color
    color40: Color
    color41: Color
    color42: Color
    color43: Color
    color44: Color
    color45: Color
    color46: Color
    color47: Color
    color48: Color
    color49: Color
    color50: Color
    color51: Color
    color52: Color
    color53: Color
    color54: Color
    color55: Color
    color56: Color
    color57: Color
    color58: Color
    color59: Color
    color60: Color
    color61: Color
    color62: Color
    color63: Color
    color64: Color
    color65: Color
    color66: Color
    color67: Color
    color68: Color
    color69: Color
    color70: Color
    color71: Color
    color72: Color
    color73: Color
    color74: Color
    color75: Color
    color76: Color
    color77: Color
    color78: Color
    color79: Color
    color80: Color
    color81: Color
    color82: Color
    color83: Color
    color84: Color
    color85: Color
    color86: Color
    color87: Color
    color88: Color
    color89: Color
    color90: Color
    color91: Color
    color92: Color
    color93: Color
    color94: Color
    color95: Color
    color96: Color
    color97: Color
    color98: Color
    color99: Color
    color100: Color
    color101: Color
    color102: Color
    color103: Color
    color104: Color
    color105: Color
    color106: Color
    color107: Color
    color108: Color
    color109: Color
    color110: Color
    color111: Color
    color112: Color
    color113: Color
    color114: Color
    color115: Color
    color116: Color
    color117: Color
    color118: Color
    color119: Color
    color120: Color
    color121: Color
    color122: Color
    color123: Color
    color124: Color
    color125: Color
    color126: Color
    color127: Color
    color128: Color
    color129: Color
    color130: Color
    color131: Color
    color132: Color
    color133: Color
    color134: Color
    color135: Color
    color136: Color
    color137: Color
    color138: Color
    color139: Color
    color140: Color
    color141: Color
    color142: Color
    color143: Color
    color144: Color
    color145: Color
    color146: Color
    color147: Color
    color148: Color
    color149: Color
    color150: Color
    color151: Color
    color152: Color
    color153: Color
    color154: Color
    color155: Color
    color156: Color
    color157: Color
    color158: Color
    color159: Color
    color160: Color
    color161: Color
    color162: Color
    color163: Color
    color164: Color
    color165: Color
    color166: Color
    color167: Color
    color168: Color
    color169: Color
    color170: Color
    color171: Color
    color172: Color
    color173: Color
    color174: Color
    color175: Color
    color176: Color
    color177: Color
    color178: Color
    color179: Color
    color180: Color
    color181: Color
    color182: Color
    color183: Color
    color184: Color
    color185: Color
    color186: Color
    color187: Color
    color188: Color
    color189: Color
    color190: Color
    color191: Color
    color192: Color
    color193: Color
    color194: Color
    color195: Color
    color196: Color
    color197: Color
    color198: Color
    color199: Color
    color200: Color
    color201: Color
    color202: Color
    color203: Color
    color204: Color
    color205: Color
    color206: Color
    color207: Color
    color208: Color
    color209: Color
    color210: Color
    color211: Color
    color212: Color
    color213: Color
    color214: Color
    color215: Color
    color216: Color
    color217: Color
    color218: Color
    color219: Color
    color220: Color
    color221: Color
    color222: Color
    color223: Color
    color224: Color
    color225: Color
    color226: Color
    color227: Color
    color228: Color
    color229: Color
    color230: Color
    color231: Color
    color232: Color
    color233: Color
    color234: Color
    color235: Color
    color236: Color
    color237: Color
    color238: Color
    color239: Color
    color240: Color
    color241: Color
    color242: Color
    color243: Color
    color244: Color
    color245: Color
    color246: Color
    color247: Color
    color248: Color
    color249: Color
    color250: Color
    color251: Color
    color252: Color
    color253: Color
    color254: Color
    color255: Color
    shell: str
    editor: str
    close_on_child_death: bool
    allow_remote_control: str
    env: typing.Dict[str, str]
    update_check_interval: float
    startup_session: typing.Union[str, None]
    clipboard_control: typing.FrozenSet[str]
    term: str
    macos_titlebar_color: int
    macos_option_as_alt: int
    macos_hide_from_tasks: bool
    macos_quit_when_last_window_closed: bool
    macos_window_resizable: bool
    macos_thicken_font: float
    macos_traditional_fullscreen: bool
    macos_show_window_title_in: str
    macos_custom_beam_cursor: bool
    linux_display_server: str
    kitty_mod: int
    clear_all_shortcuts: bool
    kitten_alias: str