#!/usr/bin/env python3
# vim:fileencoding=utf-8
# License: GPL v3 Copyright: 2018, Kovid Goyal <kovid at kovidgoyal.net>
# Launch kitty from source
import os
import sys

base = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, base)
with open(os.path.join(base, '__main__.py')) as f:
    src = f.read()
code = compile(src, f.name, 'exec')
exec(code, {'__name__': '__main__'})
